apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: riko-wabot
spec:
  serviceName: riko-wabot-service
  replicas: 1
  selector:
    matchLabels:
      app: riko-wabot
  template:
    metadata:
      labels:
        app: riko-wabot
    spec:
      containers:
        - name: riko-wabot
          image: kamuri/riko-wabot:0.1.14
          envFrom:
            - secretRef:
                name: serviceless-riko-wabot-secret
          resources:
            limits:
              cpu: "0.2"
              memory: "1G"
          volumeMounts:
            - mountPath: /app/states
              name: riko-data
  volumeClaimTemplates:
    - metadata:
        name: riko-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
