apiVersion: v1
kind: PersistentVolume
metadata:
  name: riko-wabot-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /riko-state
