apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepdanbooryu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepdanbooryu
  template:
    metadata:
      labels:
        app: deepdanbooryu
    spec:
      containers:
      - name: deepdanbooryu
        image: kamuri/deepdanbooryu:0.0.7
        args: ["server"]
        envFrom:
        - secretRef:
            name: api-deepdanbooryu-secret
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/guesser/health
            port: 8080
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            cpu: "0.1"
            memory: "100Mi"
