apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: riko-wabot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: serviceless-default
  project: default
  source:
    repoURL: https://github.com/kamuridesu/argocd-apps-test-helm.git
    path: services/serviceless/riko-wabot
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
