apiVersion: apps/v1
kind: Deployment
metadata:
  name: unrestrict-tg-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unrestrict-tg-bot
  template:
    metadata:
      labels:
        app: unrestrict-tg-bot
    spec:
      containers:
      - name: unrestrict-tg-bot
        image: kamuri/unrestrict-bot:0.0.2
        envFrom:
        - secretRef:
            name: serviceless-unrestrict-tg-bot-secret
        resources:
          limits:
            cpu: "0.2"
            memory: "500M"

