apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-webhook
  template:
    metadata:
      labels:
        app: whatsapp-webhook
    spec:
      containers:
      - name: whatsapp-webhook
        image: kamuri/test-wb-webhook:0.0.18
        envFrom:
        - secretRef:
            name: api-whatsapp-webhook-secret
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api/whatsapp-webhook/health
            port: 8000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            cpu: "0.1"
            memory: "100Mi"
