apiVersion: apps/v1
kind: Deployment
metadata:
  name: invidious
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      labels:
        app: invidious
    spec:
      containers:
      - name: invidious
        image: quay.io/invidious/invidious:2024.08.13-e319c35-arm64
        envFrom:
        - secretRef:
            name: invidious-secret
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/v1/comments/jNQXAC9IVRw
            port: 3000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /api/v1/comments/jNQXAC9IVRw
            port: 3000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            memory: 300Mi
            cpu: '0.1'
          requests:
            memory: 200Mi
            cpu: '0.05'
