apiVersion: apps/v1
kind: Deployment
metadata:
  name: invidious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      labels:
        app: invidious
    spec:
      containers:
      - name: inv-sig-helper
        image: quay.io/invidious/inv-sig-helper:master-5025e49
        args:
          - --tcp
          - 0.0.0.0:12999
        env:
          - name: RUST_LOG
            value: full
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: 200Mi
            cpu: '0.1'
          requests:
            memory: 100Mi
            cpu: '0.05'

      - name: invidious
        image: quay.io/invidious/invidious:2024.10.18-d8b893e-arm64
        envFrom:
        - secretRef:
            name: invidious-secret
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/v1/comments/jNQXAC9IVRw
            port: 3000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /api/v1/comments/jNQXAC9IVRw
            port: 3000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 10
        resources:
          limits:
            memory: 300Mi
            cpu: '0.1'
          requests:
            memory: 200Mi
            cpu: '0.05'
