apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  project: tooling
  source:
    repoURL: https://helm.datadoghq.com
    targetRevision: "3.161.1"
    chart: datadog
    helm:
      values: |
        agent:
          image:
            tagSuffix: jmx # enable jmx metrics for kafka, cassandra, tomcat, etc

        datadog:
          apiKeyExistingSecret: datadog-secret
          site: us5.datadoghq.com
          clusterName: k3s-oci

          clusterChecks:
            enabled: true

          clusterAgent:
            enabled: true

          clusterChecksRunner:
            enabled: true

          # container view: https://docs.datadoghq.com/infrastructure/containers/?tab=docker
          containerExclude: "kube_namespace:haproxy-ingress"
          containerExcludeLogs: "kube_namespace:haproxy-ingress"
          containerExcludeMetrics: "kube_namespace:haproxy-ingress"

          containerImageCollection:
            enabled: true

          remoteConfiguration:
            enabled: true

          kubelet:
            tlsVerify: false

          otlp:
            receiver:
              protocols:
                grcp:
                  enabled: true
                http:
                  enabled: true

          logLevel: WARN
          logs:
            containerCollectAll: true
            containerCollectUsingFiles: true
            enabled: true
          networkingMonitoring:
            enabled: true

          apm:
            enabled: true
            instrumentation:
              enabled: true
              targets:
                - name: "python-projects"
                  podSelector:
                    matchLabels:
                      language: python
                  ddTraceVersions:
                    python: "default"
                - name: "java-projects"
                  podSelector:
                    matchLabels:
                      language: java
                  ddTraceVersions:
                    java: "default"
                  ddTraceConfigs:
                    - name: "DD_PROFILING_ENABLED"
                      value: "auto"
                - name: "nodejs-projects"
                  podSelector:
                    matchLabels:
                      language: node-js 
                  ddTraceVersions:
                    js: "default"
                - name: "nodejs-16-projects"
                  podSelector:
                    matchLabels:
                      language: node16
                  ddTraceVersions:
                    js: "4.55.0"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
