apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-structure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kamuridesu/argocd-apps-test-helm.git
        revision: main
        directories:
          - path: structure/*
  template:
    metadata:
      name: 'argocd-{{ "{{" }}path.basename{{ "}}" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kamuridesu/argocd-apps-test-helm.git
        targetRevision: main
        path: 'structure/{{ "{{" }}path.basename{{ "}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

      destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd
