apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobalt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobalt
  template:
    metadata:
      labels:
        app: cobalt
    spec:
      containers:
      - name: cobalt
        image: kamuri/cobalt-k8s:0.0.1
        envFrom:
        - secretRef:
            name: cobalt-secret
        ports:
        - containerPort: 9000
        livenessProbe:
          httpGet:
            path: /
            port: 9000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 9000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
        resources:
          limits:
            cpu: "0.09"
            memory: "500Mi"
