apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-virtualservice
  namespace: api-default
spec:
  gateways:
    - api-default/api-gateway
  hosts:
    - api.kamuridesu.com
