apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-virtualservice
  namespace: keycloak
spec:
  gateways:
    - keycloak/keycloak-gateway
  hosts:
    - keycloak.kamuridesu.com
  http:
    - match:
        - uri:
            prefix: /
      http:
      - route:
        - destination:
            host: keycloak-service.keycloak.svc.cluster.local
            port:
              number: 8080
        headers:
          request:
            set:
              x-forwarded-proto: https
              x-forwarded-port: "443"
