apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  ingress.kubernetes.io/config-backend: |
      http-request set-header X-Forwarded-Proto https
spec:
  rules:
  - host: keycloak.kamuridesu.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: keycloak-service
            port: 
              number: 8080
  