apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3proxy
  template:
    metadata:
      labels:
        app: 3proxy
    spec:
      containers:
      - name: 3proxy
        image: ghcr.io/tarampampam/3proxy:1.9.1
        envFrom:
        - secretRef:
            name: 3proxy-secret
        ports:
        - containerPort: 1080
        - containerPort: 3128
        resources:
          limits:
            cpu: "0.1"
            memory: "80Mi"
