apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:25.0.2-0
        livenessProbe:
          httpGet:
            path: /health/ready
            port: 9000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
            httpHeaders:
              - name: Host
                value: 127.0.0.1
        args: ["start", "--cache-stack=kubernetes", "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true", "--hostname=keycloak.kamuridesu.com"]
        envFrom:
          - secretRef:
              name: keycloak-secret
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: jgroups
          containerPort: 7600
        resources:
          limits:
            memory: 1G
            cpu: '0.5'