apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
  - name: jgroups
    port: 7600
