apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: trilium-pv
  accessModes:
    - ReadWriteOnce
