apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: root/
    repoURL: https://github.com/kamuridesu/argocd-apps-test-helm.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
