apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kamuridesu/argocd-apps-test-helm.git
    path: services/networking
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true