apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: proxy
  project: default
  source:
    repoURL: https://github.com/kamuridesu/argocd-apps-test-helm.git
    path: services/proxy
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
