apiVersion: apps/v1
kind: Deployment
metadata:
  name: regex-tg-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regex-tg-bot
  template:
    metadata:
      labels:
        app: regex-tg-bot
    spec:
      containers:
      - name: regex-tg-bot
        image: kamuri/regexbot:0.0.1
        envFrom:
        - secretRef:
            name: serviceless-regex-tg-bot-secret
        resources:
          limits:
            cpu: "0.1"
            memory: "500M"
